spring:
  application:
    name: codebase-rag-engine
  docker:
    compose:
      enabled: false
      file: docker-compose.yml
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  ai:
    model:
      chat: openai      # Used OpenAI/Groq ONLY for Chat
      embedding: ollama # Use local Ollama ONLY for Embeddings

    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai/v1
      chat:
        options:
          model: llama-3.3-70b-versatile

    ollama:
      base-url: http://localhost:11434
      embedding:
        options:
          model: nomic-embed-text

    # --- VECTOR DATABASE CONFIGURATION ---
    vectorstore:
      pgvector:
        table-name: gemini_vector_store_final
        index-type: NONE
        distance-type: COSINE_DISTANCE
        dimensions: 768 # nomic-embed-text generates 768-dimensional vectors
        initialize-schema: true

kind: Application
