spring:
  application:
    name: codebase-rag-engine
  docker:
    compose:
      enabled: false
      file: docker-compose.yml
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        project-id: dummy-project-id-chat
        location: us-central1
        chat:
          options:
            model: gemini-2.0-flash
        embedding:
          api-key: ${GEMINI_API_KEY}
          project-id: dummy-project-id-embedding
          location: us-central1
          options:
            model: text-embedding-004
            # We removed the broken output-dimensionality command
    vectorstore:
      pgvector:
        table-name: gemini_vector_store_final # <-- Forces a brand new, clean table
        index-type: NONE # <-- Bypasses the 2000 limit completely!
        distance-type: COSINE_DISTANCE
        dimensions: 3072 # <-- Maximum quality Google vectors
        initialize-schema: true